### ISSUE TITLE
Submit Abstract and Give Talk at WikiConference North America -  How to Create Wikimedia Working Groups for GLAMs

### ISSUE THREAD

**Issue by JJDear83** [JJDear83/BHL-WIKI-Working-Group#32]
As a BHL Wiki Founding Member, I want to discuss how to create working groups for GLAMS so that the broader community can understand: 

1. Group formation timeline
2. Experience and activities
3. Results
4. Supporting others interested in starting a Wikimedia Working Group.

Abstract Link[https://wikiconference.org/wiki/Submissions:2024/How_to_create_Wikimedia_Working_Groups_for_GLAMs](url)

**Comment by JJDear83** [comment]
Added abstract link this is in TESTING. May need to work on some presentation materials for @GiFontenelle. Let us know.

**Comment by GiFontenelle** [comment]
I presented the session [How to create Wikimedia Working Groups for GLAMs](https://wikiconference.org/wiki/Submissions:2024/How_to_create_Wikimedia_Working_Groups_for_GLAMs) on October 5, Saturday, from 12 to 1 pm. The slide deck is [here](https://docs.google.com/presentation/d/1ma7Z6CRy_QTMMRqxLe2z0GXA5sxSTSiyCvW_MLMK-Ro/edit?usp=sharing). Jake Orlowitz participated and, not only helped me to present the session, but also added some slides and reviewed my part of the presentation as well. 

Siobhan Leachman shared a quote about her BHL-WG experience (slide 28). Siobhan also watched the presentation live and shared a great comment during the presentation, on the chat. Richard Naples was in the room in person and shared a few thoughts, especially after the presentation.

The session was very well received, both by the general movement, as well as Wikimedians in Residence and Foundation staff present. 

I will share the recording link when available.
