### ISSUE TITLE
Collect Wiki usergroup formation criteria

### ISSUE THREAD

**Issue by JJDear83** [JJDear83/BHL-WIKI-Working-Group#6]

**Comment by jorlowitz** [comment]
Document complete: 
https://docs.google.com/document/d/13a2OW1A7i2d2YIIBWzn0MsbabJS-SOQuHJSyJZPcM2c/edit?usp=sharing

**Comment by JJDear83** [comment]
Adding @lubianat , @SiobhanLeachman , and @GiFontenelle for visibility on this. Jake has completed his review. Thank you!! 👍
